# fly.toml app configuration file generated for springboot-rest-api-kfdtkw on 2025-03-30T23:24:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'springboot-rest-api-kfdtkw'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
